Repository cs130-w21/book.ar, pull requests merged in 2021-03, with the labels that each got.

#44 feat: Take preferences from user while registering
  BookAr/package.json
  BookAr/src/screens/RegistrationScreen/RegistrationScreen.js
  BookAr/src/screens/RegistrationScreen/styles.js
  BookAr/yarn.lock
Labels: feature

#43 feat: Link Cloud Vision API data with Recommendation server
  BookAr/src/screens/SelectScreen/BookListItem.js
  BookAr/src/screens/SelectScreen/SelectScreen.js
  BookAr/src/screens/SelectScreen/styles.js
  BookAr/src/utils/cloud_vision.ts
Labels: feature

#50 feat: Miscellaneous improvements
  BookAr/src/screens/SelectScreen/SelectScreen.js
  BookAr/src/screens/SelectScreen/styles.js
  BookAr/src/types.ts
  BookAr/src/utils/cloud_vision.ts
  BookAr/src/utils/firebase.js
  BookAr/src/utils/firebase.ts
  BookAr/src/utils/image_picker.js
  BookAr/src/utils/image_picker.ts
  BookAr/src/utils/recommender.js
  server/app.py
  server/models.py
  server/tests/test_app.py
Labels: feature

#52 chore: add github action for jsdocs creation
  .github/workflows/jsdocs.yml
Labels: chore

#53 fix: Change ACTION_DEPLOY_KEY to GITHUB_TOKEN
  .github/workflows/jsdocs.yml
Labels: bug

#54 fix: another one -DJ Khaled
  .github/workflows/jsdocs.yml
Labels: bug

#56 fix: Add recurse: true to JSDoc action
  .github/workflows/jsdocs.yml
Labels: chore

#57 feat: Improve UI and add more functionality for preferences
  BookAr/src/common/BookListItem/BookListItem.js
  BookAr/src/common/BookListItem/styles.js
  BookAr/src/screens/HomeScreen/HomeScreen.js
  BookAr/src/screens/ProfileScreen/ProfileScreen.js
  BookAr/src/screens/SelectScreen/BookModal.js
  BookAr/src/screens/SelectScreen/SelectScreen.js
  BookAr/src/screens/SelectScreen/styles.js
  BookAr/src/utils/index.js
  BookAr/src/utils/recommender.js
Labels: feature

#55 feat: add more JSDocs to rest of components
  BookAr/App.js
  BookAr/src/HomeTabs.js
  BookAr/src/common/BookListItem/BookListItem.js
  BookAr/src/screens/HomeScreen/HomeScreen.js
  BookAr/src/screens/LoginScreen/LoginScreen.js
  BookAr/src/screens/ProfileScreen/ProfileScreen.js
  BookAr/src/screens/RegistrationScreen/RegistrationScreen.js
  BookAr/src/screens/index.js
  BookAr/src/utils/Button.js
  BookAr/src/utils/index.js
Labels: chore

#60 fix: Made some minor bugfixes
  BookAr/src/common/BookListItem/BookListItem.js
  BookAr/src/utils/recommender.js
Labels: bug
